### PR TITLE
Rely on local environment instead of Bluestar2

### PR DESCRIPTION
**Pull request by Mackiovello**
@per-samuelsson FYI, I'm not sure if this is correct. Is this shared host code even going to be used with the new shared host?

See also https://starcounter.slack.com/archives/C5Q4Y78F5/p1544602720041900

### CODE REVIEW

**Comment by Mackiovello** [comment]
Build: https://teamcity.starcounter.org/viewLog.html?buildId=82487&tab=buildResultsDiv&buildTypeId=Bifrost_UmbrellaIntegrationNovaBuild

**Comment by Mackiovello** [comment]
Check that it'll work with the level0 qp-dev branch as requested by Björn: https://teamcity.starcounter.org/viewLog.html?buildId=82489&tab=buildResultsDiv&buildTypeId=Bifrost_IntNovaWinDbg

**Comment by per-samuelsson** [comment]
> @per-samuelsson FYI, I'm not sure if this is correct. Is this shared host code even going to be used with the new shared host?

It's not, no. I've been given it some thought last few days actually, knowing we have code and a pending PR (#87). 

We've currently abandoned the idea of code-generating host in favor of the one I'm working now (dynamic load in ALCs), but I don't want to throw the source-code generating one fully just yet, if we find something that needs us to go back to that (although unlikely).

I'm not sure what the right thing to do is. I guess we could remove all shared hosting bits from this repo and close the #87 PR, but let that branch live for a while still?

**Comment by Mackiovello** [comment]
> I'm not sure what the right thing to do is. I guess we could remove all shared hosting bits from this repo and close the #87 PR, but let that branch live for a while still?

It's not hurting to have the code in here a little longer, so let's keep it around but close #87 without deleting the branch. When we've established that we're not going to use this shared hosting implementation, we delete it.

**Pull request merged**
